resources:
  jobs:
    reporting_api_pipeline:

      name: reporting-api-pipeline

      tasks:
        - task_key: reporting-api-task

          spark_python_task:
            python_file: ../src/etls/reporting_api.py

          environment_key: serverless

      environments:
        - environment_key: serverless
          spec:
            client: "1"

      schedule:
        quartz_cron_expression: "0 0 9 * * ?"
        timezone_id: "Asia/Kolkata"
        pause_status: UNPAUSED